-- auto-generated definition
DROP TABLE TB_TUTORIAL;

CREATE TABLE TB_TUTORIAL
(
    ID NUMBER NOT NULL,
    TITLE VARCHAR2(256),
    DESCRIPTION VARCHAR2(1000),
    PUBLISHED CHAR(1),
    DELETE_YN CHAR(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(30),
    UPDATE_TIME VARCHAR2(30),
    DELETE_TIME VARCHAR2(30)
);

ALTER TABLE TB_TUTORIAL ADD CONSTRAINT PK_TUTORIAL_ID PRIMARY KEY(ID);

CREATE SEQUENCE SQ_TUTORIAL
INCREMENT BY 1 START WITH 1
MINVALUE 1
MAXVALUE 99999999;
