DELETE FROM DEPARTMENT
WHERE
    DNO = 10;

ROLLBACK;

CREATE TABLE DEPARTMENT2
    AS
        SELECT
            *
        FROM
            DEPARTMENT;

INSERT INTO DEPARTMENT2 (
    DNO,
    DNAME,
    LOC
)
        --model의 Dept의 값이 넘어옴
 VALUES (
    10,
    '일감찬',
    '부산'
);

CREATE TABLE TB_MEMBER (
    "USER_ID"     VARCHAR2(255 BYTE)
        NOT NULL ENABLE,
    "USER_PW"     VARCHAR2(256 BYTE),
    "USER_NAME"   VARCHAR2(255 BYTE),
    "USER_AUTH"   VARCHAR2(255 BYTE),
    "APPEND_DATE" VARCHAR2(255 BYTE),
    "UPDATE_DATE" VARCHAR2(255 BYTE),
    CONSTRAINT "PK_TB_MEMBER_USER_ID" PRIMARY KEY ( "USER_ID" )
);

ALTER TABLE TB_MEMBER DROP COLUMN USER_PW; 

ALTER TABLE TB_BOARD MODIFY INSERT_TIME DATE;
ALTER TABLE TB_BOARD MODIFY UPDATE_TIME DATE;
ALTER TABLE TB_BOARD MODIFY DELETE_TIME DATE;