CREATE TABLE TB_BOARD2
    AS
        SELECT
            *
        FROM
            TB_BOARD
        WHERE
            1 = 2;

CREATE SEQUENCE "SCOTT"."SQ_DEPT4" MINVALUE 1 MAXVALUE 100000 INCREMENT BY 10 START WITH 10 CACHE 20 NOORDER NOCYCLE;

UPDATE DEPARTMENT
SET
    DNAME = '강감찬',
    LOC = '사직'
WHERE
    DNO = 10;

----------------------------------------------------------
CREATE TABLE TB_BOARD (
    IDX         NUMBER NOT NULL,
    TITLE       VARCHAR2(256),
    CONTENT     VARCHAR2(256),
    WRITER      VARCHAR2(256),
    VIEW_CNT    NUMBER DEFAULT 0,
    NOTICE_YN   CHAR(1) DEFAULT 'N',
    SECRET_YN   CHAR(1) DEFAULT 'N',
    DELETE_YN   CHAR(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(256),
    UPDATE_TIME VARCHAR2(256),
    DELETE_TIME VARCHAR2(256)
);

ALTER TABLE TB_BOARD ADD CONSTRAINT PK_TB_BOARD_IDX PRIMARY KEY ( IDX );

CREATE SEQUENCE SQ_TB_BOARD MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;