CREATE TABLE EMPLOYEE2 AS SELECT * FROM EMP WHERE 1 = 2;

ALTER TABLE EMPLOYEE2
RENAME COLUMN MGR TO MANAGER;

ALTER TABLE EMPLOYEE2
RENAME COLUMN SAL TO SALARY;

ALTER TABLE EMPLOYEE2
RENAME COLUMN COMM TO COMMISSION;

ALTER TABLE EMPLOYEE2
RENAME COLUMN EMPNO TO ENO;

ALTER TABLE EMPLOYEE2
RENAME COLUMN DEPTNO TO DNO;

CREATE SEQUENCE SQ_EMP2 INCREMENT BY 1 START WITH 1;

ALTER TABLE EMPLOYEE2
MODIFY HIREDATE VARCHAR2(100);

TRUNCATE TABLE EMPLOYEE2;