CREATE TABLE TB_MEMBER (
    USER_ID     VARCHAR2(255) NOT NULL,
    USER_NAME   VARCHAR2(255),
    USER_AUTH   VARCHAR2(255),
    APPEND_DATE VARCHAR2(255),
    UPDATE_DATE VARCHAR2(255)
);

ALTER TABLE TB_MEMBER ADD CONSTRAINT PK_TB_MEMBER_USER_ID PRIMARY KEY ( USER_ID );


CREATE TABLE DEPARTMENT4 AS SELECT * FROM DEPARTMENT WHERE 1 = 2;