CREATE TABLE TB_COMPLAIN (
    ID          NUMBER PRIMARY KEY
    ,TITLE       VARCHAR2(100)
    ,CONTENT     VARCHAR2(500)
    ,TARGET_PAGE VARCHAR2(100)
    ,WRITER      VARCHAR2(100)
    ,DELETE_YN   CHAR(1) DEFAULT 'N'
    ,INSERT_TIME VARCHAR2(255)
    ,UPDATE_TIME VARCHAR2(255)
    ,DELETE_TIME VARCHAR2(255)
);

CREATE SEQUENCE SQ_COMPLAIN START WITH 1 INCREMENT BY 1 MINVALUE 1;