-- ?•„?ž˜ ?…Œ?´ë¸?, ? œ?•½ì¡°ê±´, ?‹œ???Š¤ ?´ë¦„ì„ ? ‘ë¯¸ì–´ë¡? ?žê¸? ?˜ë¬¸ì´?‹ˆ?…œ?„ ë¶™ì—¬?„œ ?ƒ?„±?•˜?‹œ?˜¤.
-- 1) ?…‡?…?ž˜ ?…Œ?´ë¸”ëª…?— TB_BOARD_EXAM_XXX : ??— ?žê¸? ?´ë¦? ?´?‹ˆ?…œ?„ ?„£?œ¼?‹œ?š”.
-- 2) ?•„?ž˜ PRIMARY KEY ?´ë¦„ë„ PK_BOARD_EXAM_XXX_ID ë¡? ë³?ê²½í•˜?‹œ?˜¤.
-- 3) ?•„?ž˜ SQ_BOARD_EXAM_XXX ?œ¼ë¡? ?´ë¦„ì„ ë³?ê²½í•˜?‹œ?˜¤.
DROP TABLE TB_BOARD_EXAM;

CREATE TABLE TB_BOARD_EXAM_LGM (
  ID NUMBER NOT NULL ,
  BOARD_TITLE VARCHAR2(256) ,
  BOARD_CONTENT VARCHAR2(255),
  BOARD_WRITER VARCHAR2(255) ,
  VIEW_CNT NUMBER DEFAULT 0,
  DELETE_FLAG CHAR(1) DEFAULT 'N',
  INSERT_TIME VARCHAR2(50),
  UPDATE_TIME VARCHAR2(50),
  DELETE_TIME VARCHAR2(50)
);

ALTER TABLE TB_BOARD_EXAM_LGM ADD CONSTRAINT PK_BOARD_EXAM_ID PRIMARY KEY(ID);

DROP SEQUENCE SQ_BOARD_EXAM;

CREATE SEQUENCE  SQ_BOARD_EXAM_LGM
MINVALUE 1 MAXVALUE 99999999 
INCREMENT BY 1 START WITH 1;









