-- ?•„?ž˜ ?…Œ?´ë¸?, ? œ?•½ì¡°ê±´, ?‹œ???Š¤ ?´ë¦„ì„ ? ‘ë¯¸ì–´ë¡? ?žê¸? ?˜ë¬¸ì´?‹ˆ?…œ?„ ë¶™ì—¬?„œ ?ƒ?„±?•˜?‹œ?˜¤.
-- 1) ?…‡?…?ž˜ ?…Œ?´ë¸”ëª…?— TB_COMMENT_EXAM_XXX : ??— ?žê¸? ?´ë¦? ?´?‹ˆ?…œ?„ ?„£?œ¼?‹œ?š”.
-- 2) ?•„?ž˜ PRIMARY KEY ?´ë¦„ë„ PK_COMMENT_EXAM_XXX_ID ë¡? ë³?ê²½í•˜?‹œ?˜¤.
-- 3) ?•„?ž˜ SQ_COMMENT_EXAM_XXX ?œ¼ë¡? ?´ë¦„ì„ ë³?ê²½í•˜?‹œ?˜¤.
DROP TABLE TB_COMMENT_EXAM;

CREATE TABLE TB_COMMENT_EXAM_LGM (
    ID NUMBER NOT NULL,
    BOARD_ID NUMBER ,
    COMMENT_CONTENT VARCHAR2(3000) ,
    COMMENT_WRITER VARCHAR2(256) ,
    DELETE_FLAG  CHAR(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(50) ,
    UPDATE_TIME VARCHAR2(50) ,
    DELETE_TIME VARCHAR2(50)
);

ALTER TABLE TB_COMMENT_EXAM_LGM ADD CONSTRAINT PK_COMMENT_EXAM_ID PRIMARY KEY(ID);

DROP SEQUENCE SQ_COMMENT_EXAM;

CREATE SEQUENCE SQ_COMMENT_EXAM_LGM
INCREMENT BY 1 START WITH 1
MINVALUE 1
MAXVALUE 99999999;