    CREATE TABLE TB_CUSTOMER_LGM 
   (	"ID" NUMBER(19,0) NOT NULL , 
	"FIRST_NAME" VARCHAR2(255 BYTE) , 
	"LAST_NAME" VARCHAR2(255 BYTE) , 
	"EMAIL" VARCHAR2(255 BYTE) , 
	"PHONE" VARCHAR2(255 BYTE) , 
	"DELETE_YN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"INSERT_TIME" VARCHAR2(255 BYTE) , 
	"UPDATE_TIME" VARCHAR2(255 BYTE) , 
	"DELETE_TIME" VARCHAR2(255 BYTE) , 
	 PRIMARY KEY ("ID")
    );
    
    CREATE SEQUENCE SQ_CUSTOMER
    INCREMENT BY 1 START WITH 1
    MINVALUE 1 MAXVALUE 99999999;
    
    
    
    