DROP TABLE TB_FILES;

CREATE TABLE TB_FILES(
    ID VARCHAR2(100),
    NAME VARCHAR2(1000),
    TYPE VARCHAR2(1000),
    DATA BLOB --데이터베이스에 이미지를 처리하는 부분
);

ALTER TABLE TB_FILES ADD CONSTRAINTS PK_FILES PRIMARY KEY(ID);

SELECT * FROM TB_FILES;


    