CREATE TABLE TB_FREE (
    ID          NUMBER PRIMARY KEY
    ,TITLE       VARCHAR2(100)
    ,CONTENT     VARCHAR2(500)
    ,WRITER      VARCHAR2(100)
    ,DELETE_YN   CHAR(1) DEFAULT 'N'
    ,INSERT_TIME VARCHAR2(255)
    ,UPDATE_TIME VARCHAR2(255)
    ,DELETE_TIME VARCHAR2(255)
);

CREATE SEQUENCE SQ_FREE START WITH 0 INCREMENT BY 1 MINVALUE 0;