DROP TABLE TB_FILES;

CREATE TABLE TB_FILES (
    ID   VARCHAR2(100),
    NAME VARCHAR2(1000),
    TYPE VARCHAR2(1000),
    DATA BLOB -- 이미지를 담는 컬럼 자료형
);

ALTER TABLE TB_FILES ADD CONSTRAINTS PK_FILES PRIMARY
KEY(ID);

CREATE SEQUENCE SQ_FILES INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 99999999;

SELECT
    *
FROM
    TB_FILES;


    